import { expect, test } from "bun:test"
import { normalize, type Template } from "../src/normalize.js"

const HASH = "a".repeat(32)

const template = (): Template => ({
  Metadata: { "aws:cdk:path": "Stack" },
  Parameters: {
    BootstrapVersion: { Type: "String" },
    AssetParam: { Type: "String" },
  },
  Rules: { CheckBootstrapVersion: {}, Other: {} },
  Resources: {
    Fn: {
      Type: "AWS::Lambda::Function",
      Metadata: { "aws:asset:path": "asset.abc" },
      Properties: {
        Code: { S3Key: "abc.zip" },
        Tags: [{ Key: "team", Value: "infra" }],
      },
    },
    [`FnCurrentVersionABCDEF12${HASH}`]: { Type: "AWS::Lambda::Version" },
  },
})

/**
 * Defaults are contractual. Projects carry snapshots generated by
 * jest-cdk-snapshot, and a changed default rewrites them silently.
 */
const expectations: [
  label: string,
  read: (template: Template) => unknown,
  expected: unknown,
][] = [
  [
    "drops the bootstrap parameter",
    (t) => t.Parameters.BootstrapVersion,
    undefined,
  ],
  ["drops the bootstrap rule", (t) => t.Rules.CheckBootstrapVersion, undefined],
  [
    "keeps other parameters",
    (t) => t.Parameters.AssetParam,
    { Type: "String" },
  ],
  ["keeps other rules", (t) => t.Rules.Other, {}],
  [
    "keeps asset code",
    (t) => t.Resources.Fn.Properties.Code,
    { S3Key: "abc.zip" },
  ],
  [
    "keeps current version hashes",
    (t) => Object.keys(t.Resources).includes(`FnCurrentVersionABCDEF12${HASH}`),
    true,
  ],
  ["keeps template metadata", (t) => t.Metadata, { "aws:cdk:path": "Stack" }],
  [
    "keeps resource metadata",
    (t) => t.Resources.Fn.Metadata,
    { "aws:asset:path": "asset.abc" },
  ],
  [
    "keeps tags",
    (t) => t.Resources.Fn.Properties.Tags,
    [{ Key: "team", Value: "infra" }],
  ],
  ["keeps every resource", (t) => Object.keys(t.Resources).length, 2],
]

test.each(expectations)("by default %s", (_label, read, expected) => {
  expect(read(normalize(template()))).toEqual(expected)
})

test("removes a section that the bootstrap entry emptied", () => {
  const result = normalize({
    Parameters: { BootstrapVersion: {} },
    Rules: { CheckBootstrapVersion: {} },
  })

  expect(result.Parameters).toBeUndefined()
  expect(result.Rules).toBeUndefined()
})
